<#
.SYNOPSIS
  One-line Windows installer for the `agents` CLI (D-17).

.DESCRIPTION
  Drops a PowerShell wrapper at $env:LOCALAPPDATA\agents\bin\agents.ps1
  and clones the agents_cli package into $env:LOCALAPPDATA\agents\lib\.
  Set $env:AGENTS_REF to choose a marketplace branch (default 'main').

  Works on Windows PowerShell 5.1 and PowerShell 7+.

.EXAMPLE
  irm https://raw.githubusercontent.com/DgxSparkLabs/marketplace/main/install.ps1 | iex

.EXAMPLE
  powershell -ExecutionPolicy Bypass -File install.ps1
#>

$ErrorActionPreference = 'Stop'

$Dest = if ($env:AGENTS_DEST) { $env:AGENTS_DEST } else { "$env:LOCALAPPDATA\agents\bin\agents.ps1" }
$Lib  = if ($env:AGENTS_LIB)  { $env:AGENTS_LIB }  else { "$env:LOCALAPPDATA\agents\lib" }
$Ref  = if ($env:AGENTS_REF)  { $env:AGENTS_REF }  else { 'main' }
$RepoUrl = if ($env:AGENTS_MARKETPLACE_URL) { $env:AGENTS_MARKETPLACE_URL } else { 'https://github.com/DgxSparkLabs/marketplace' }

# Locate Python (>= 3.11).
$Python = $env:AGENTS_PYTHON
if (-not $Python) {
    foreach ($candidate in @('python', 'python3', 'py')) {
        $cmd = Get-Command $candidate -ErrorAction SilentlyContinue
        if ($cmd) { $Python = $cmd.Source; break }
    }
}
if (-not $Python) {
    Write-Error "Python 3.11+ not found on PATH. Install from https://www.python.org/downloads/ first."
    exit 1
}
$verCheck = & $Python -c "import sys; sys.exit(0 if sys.version_info >= (3, 11) else 1)"
if ($LASTEXITCODE -ne 0) {
    Write-Error "Python 3.11+ required (found $(& $Python --version 2>&1))."
    exit 1
}

# Locate git.
if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
    Write-Error "git not found on PATH. Install from https://git-scm.com/download/win first."
    exit 1
}

New-Item -ItemType Directory -Force -Path (Split-Path $Dest) | Out-Null
New-Item -ItemType Directory -Force -Path $Lib | Out-Null

$Tmp = Join-Path ([System.IO.Path]::GetTempPath()) ("agents-install-" + [System.Guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Force -Path $Tmp | Out-Null
try {
    Write-Host "Cloning $RepoUrl @ $Ref ..."
    & git clone --depth 1 --branch $Ref $RepoUrl (Join-Path $Tmp 'marketplace') | Out-Null
    if ($LASTEXITCODE -ne 0) { throw "git clone failed." }

    foreach ($pkg in @('agents_cli', 'converters')) {
        $src = Join-Path $Tmp "marketplace\scripts\$pkg"
        $dst = Join-Path $Lib  $pkg
        if (Test-Path $dst) { Remove-Item -Recurse -Force $dst }
        Copy-Item -Recurse -Force -Path $src -Destination $dst
    }

    # Wrapper — PowerShell script that sets PYTHONPATH and execs python.
    $wrapper = @"
# Auto-generated by install.ps1.
`$env:PYTHONPATH = '$Lib' + [System.IO.Path]::PathSeparator + `$env:PYTHONPATH
& '$Python' -m agents_cli.main @args
exit `$LASTEXITCODE
"@
    Set-Content -Path $Dest -Value $wrapper -Encoding UTF8

    Write-Host "Installed 'agents' to $Dest"
    Write-Host "Library at      $Lib"

    $binDir = Split-Path $Dest
    $pathDirs = $env:PATH -split [System.IO.Path]::PathSeparator
    if ($pathDirs -notcontains $binDir) {
        Write-Host "note: $binDir is not on PATH. Add it (User env) so `agents` resolves directly."
    }
}
finally {
    Remove-Item -Recurse -Force $Tmp -ErrorAction SilentlyContinue
}
