#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""
bundles.py — Bundle dataclass, loader, and plugin builder.

Catalog schema (bundles-only after DI refactor):

  [bundle.<name>]
  description = "Human-readable description"   # optional
  members = ["skill:foo", "bundle:bar", ...]   # required

Member syntax: "<ref_type>:<name>"
  - "skill:telegram-notify"  → individual plugin named "skill-telegram-notify"
  - "rule:no-ai-credit"      → individual plugin named "rule-no-ai-credit"
  - "bundle:communication-skills" → bundle plugin named "bundle-communication-skills"

Reserved names: "<prefix>-all" for each construct prefix.
  load_bundles raises ValueError if catalog tries to define one of these.
  They are code-generated by Phase 2b of generate_manifest.py (decision #23).
"""

from __future__ import annotations

import tomllib
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Literal

if TYPE_CHECKING:
    from constructs import Construct

from utils import _marketplace_author, _marketplace_version


@dataclass(frozen=True)
class BundleMember:
    """A single member reference within a Bundle."""

    ref_type: Literal["plugin", "bundle"]  # what kind of thing is referenced
    prefix: str | None                     # construct prefix if ref_type=="plugin", else None
    name: str                              # plugin instance name OR bundle name

    @classmethod
    def from_str(cls, s: str) -> "BundleMember":
        """Parse 'skill:telegram-notify' or 'bundle:communication-skills'.

        Raises ValueError on malformed input (missing colon, unknown ref_type,
        or empty name component).
        """
        if ":" not in s:
            raise ValueError(
                f"Bundle member '{s}' has no colon — expected '<kind>:<name>' syntax, "
                f"e.g. 'skill:telegram-notify' or 'bundle:communication-skills'."
            )
        left, right = s.split(":", 1)
        left = left.strip()
        right = right.strip()
        if not left or not right:
            raise ValueError(
                f"Bundle member '{s}' has empty kind or name — "
                f"expected '<kind>:<name>' syntax."
            )
        if left == "bundle":
            return cls(ref_type="bundle", prefix=None, name=right)
        # All other left-hand sides are treated as construct prefixes (plugin refs)
        return cls(ref_type="plugin", prefix=left, name=right)


@dataclass(frozen=True)
class Bundle:
    """A user-declared bundle from catalog.toml."""

    name: str
    description: str | None
    members: list[BundleMember]

    @property
    def category(self) -> str:
        """marketplace.json category for bundle plugins."""
        return "bundle"

    def generated_plugin_name(self) -> str:
        """The plugin name used in marketplace.json and _generated/."""
        return f"bundle-{self.name}"

    def resolve_dependencies(self, constructs: "dict[str, Construct]") -> list[str]:
        """Resolve member references to plugin name strings.

        Returns:
          - For plugin members: "<prefix>-<name>"  (e.g., "skill-telegram-notify")
          - For bundle members: "bundle-<name>"    (e.g., "bundle-communication-skills")
        """
        deps: list[str] = []
        for m in self.members:
            if m.ref_type == "bundle":
                deps.append(f"bundle-{m.name}")
            else:
                deps.append(f"{m.prefix}-{m.name}")
        return deps


def load_bundles(
    catalog_path: Path, constructs: "dict[str, Construct]"
) -> list[Bundle]:
    """Parse catalog.toml [bundle.*] blocks. Validates schema.

    Raises ValueError if:
      - a bundle is missing the 'members' field
      - a member string has invalid syntax

    Note: per-construct catch-all bundles (bundle-<prefix>-all) were retired
    2026-05-27. They previously had reserved names enforced here; the
    reservation is gone now and the catalog may use any name.
    """
    with open(catalog_path, "rb") as f:
        data = tomllib.load(f)

    bundles: list[Bundle] = []

    for name, spec in data.get("bundle", {}).items():
        members_raw = spec.get("members", [])
        if not members_raw:
            raise ValueError(
                f"Bundle '{name}': must specify 'members' (a list of plugin or bundle "
                f"references like 'skill:foo' or 'bundle:bar')."
            )

        members = [BundleMember.from_str(m) for m in members_raw]
        bundles.append(Bundle(
            name=name,
            description=spec.get("description"),
            members=members,
        ))

    return bundles


def _auto_description(deps: list[str]) -> str:
    """Fallback description when a bundle has none declared in catalog."""
    if len(deps) <= 3:
        return f"Bundle containing: {', '.join(deps)}"
    return f"Bundle containing {len(deps)} items: {', '.join(deps[:3])}, ..."


def build_bundle_plugin_json(bundle: Bundle, deps: list[str]) -> dict:
    """Build the plugin.json content for a catalog-declared bundle."""
    description = bundle.description or _auto_description(deps)
    return {
        "name": bundle.generated_plugin_name(),
        "version": _marketplace_version(),
        "description": description,
        "author": _marketplace_author(),
        "dependencies": deps,
    }
